### ISSUE TITLE
No module named 'lib.roi_layers'

### ISSUE THREAD

**Issue by Aitasai** [syshensyshen/pva-faster-rcnn-pytorch-1.0#1]
Traceback (most recent call last):
  File "trainval_net.py", line 37, in <module>
    from models.lite import lite_faster_rcnn
  File "/media/srh/000D93FB00057FA2/zym/pvanew/pva-faster-rcnn-pytorch-1.0-master/models/lite.py", line 7, in <module>
    from models.pva_faster_rcnn import pva_faster_rcnn
  File "/media/srh/000D93FB00057FA2/zym/pvanew/pva-faster-rcnn-pytorch-1.0-master/models/pva_faster_rcnn.py", line 10, in <module>
    from lib.rpn.rpn_regression import _RPN
  File "/media/srh/000D93FB00057FA2/zym/pvanew/pva-faster-rcnn-pytorch-1.0-master/lib/rpn/rpn_regression.py", line 14, in <module>
    from lib.rpn.proposal_layer import ProposalLayer
  File "/media/srh/000D93FB00057FA2/zym/pvanew/pva-faster-rcnn-pytorch-1.0-master/lib/rpn/proposal_layer.py", line 20, in <module>
    from lib.roi_layers.nms import nms
ModuleNotFoundError: No module named 'lib.roi_layers'

**Comment by syshensyshen** [comment]
this module is older version，
please using this code
from torchvision.ops import RoIPool as ROIPoolingLayer
from torchvision.ops import RoIAlign as ROIAlignLayer

**Comment by syshensyshen** [comment]
@Aitasai or you can use the lastest commit code
